import{processTrackingLabels as e}from"../../../../martech/attributes.js";import{getConfig as t,shouldBlockFreeTrialLinks as a}from"../../../../utils/utils.js";import{fetchAndProcessPlainHtml as n,getActiveLink as r,icons as s,isDesktop as i,logErrorFor as l,selectors as o,setActiveDropdown as c,toFragment as d,trigger as m,yieldToMain as p,addMepHighlightAndTargetId as u,getAsyncDropdownCount as f,setActiveLink as v,getDisableAEDState as h,hasActiveLink as g}from"../utilities.js";function y(a,n){if("string"!=typeof a||!a.length)return a;let r=e(a,t(),30);return r="number"==typeof n?`${r}-${n}`:r,r}const $=(e,t)=>{if(!(e instanceof HTMLElement))return null;const a=d`<div class="feds-menu-headline">
      ${e.textContent.trim()}
    </div>`,n=e=>{i.matches||(m({element:a,event:e,type:"headline"}),c(a))},r=()=>{i.matches?(a.setAttribute("role","heading"),a.removeAttribute("tabindex"),a.setAttribute("aria-level",2),a.removeAttribute("aria-haspopup",!0),a.removeAttribute("aria-expanded",!1),a.removeAttribute("daa-ll"),a.removeEventListener("click",n)):(a.setAttribute("role","button"),a.setAttribute("tabindex",0),a.removeAttribute("aria-level"),a.setAttribute("aria-haspopup",!0),a.setAttribute("aria-expanded",!1),a.setAttribute("daa-ll",y(a.textContent,t)),a.addEventListener("click",n))};return r(),i.addEventListener("change",r),e.remove(),a},L=(e,t)=>{if(!(e instanceof HTMLElement&&e.querySelector("a")))return"";const a=e.querySelector("picture"),n=e.querySelector("a"),r=e.querySelector("p:nth-child(2)"),s=[...e.classList].filter((e=>"link-group"!==e)).map((e=>`feds-navLink--${e}`)),i=a?d`<div class="feds-navLink-image">${a}</div>`:"",l=r?d`<div class="feds-navLink-description">${r.textContent}</div>`:"",o=n?d`<div class="feds-navLink-content">
      <div class="feds-navLink-title">${n.textContent}</div>
      ${l}
    </div>`:"";let c=d`<a
    href="${n.href}"
    class="feds-navLink${s.length?` ${s.join(" ")}`:""}"
    daa-ll="${y(n.textContent,t)}">
      ${i}
      ${o}
    </a>`;return c.classList.contains("feds-navLink--header")&&(c=d`<div
      role="heading"
      aria-level="3"
      class="feds-navLink${s.length?` ${s.join(" ")}`:""}"
      daa-ll="${y(n.textContent,t)}">
        ${i}
        ${o}
      </div>`),n?.target&&(c.target=n.target),c},E=({elem:e,className:n="feds-navLink",itemIndex:r={position:0}}={})=>{const s=e=>{if(r.position+=1,e.matches(".link-group"))return L(e,r.position);if("STRONG"===e.parentElement.tagName||"EM"===e.parentElement.tagName){const n="EM"===e.parentElement.tagName?"secondaryCta":"primaryCta";return e.parentElement.replaceWith(e),function({elem:e,type:n="primaryCta",index:r}={}){if(a({button:e,localePrefix:t()?.locale?.prefix,parent:e.parentElement}))return null;const s="secondaryCta"===n?"secondary":"primary",i=e.cloneNode(!0);return i.className=`feds-cta feds-cta--${s}`,i.setAttribute("daa-ll",y(i.textContent,r)),d`
    <div class="feds-cta-wrapper">
      ${i}
    </div>`}({elem:e,type:n,index:r.position})}return e.setAttribute("daa-ll",y(e.textContent,r.position)),e.classList.add(n),e},i="a, .link-group";return e.matches(i)?d`<li>${s(e)}</li>`:(e.querySelectorAll(i).forEach((e=>{e.replaceWith(s(e))})),e)},S=e=>{const t=e.querySelector("a"),a=e.querySelector("picture"),n=t instanceof HTMLElement?d`<a class="feds-image" href="${t.href}" daa-ll="gnav-image">${a}</a>`:d`<div class="feds-image">${a}</div>`;return e.replaceChildren(n),d`<div class="feds-image-wrapper">${e}</div>`},x=(e,t)=>{const a=e.matches(".dark"),n=e.matches(".image-only"),r=e.querySelector("p > strong"),s=e.querySelector("picture");if(!n){const t=[...e.querySelectorAll(":scope > div")].find((e=>!(e.querySelector("picture")instanceof HTMLElement)));t?.classList.add("feds-promo-content")}if(r?.textContent.trim()){const e=d`<h2 class="feds-promo-header">
        ${r.textContent.trim()}
      </h2>`;r.parentElement.replaceWith(e)}E({elem:e,className:"feds-promo-link",index:t});return s instanceof HTMLElement&&(()=>{const t=e.querySelector("a"),a=s.closest(`${o.gnavPromo} > div`);let r;r=t instanceof HTMLElement?d`<a class="feds-promo-image" href="${t.href}" daa-ll="promo-image">
          ${s}
        </a>`:d`<div class="feds-promo-image">
          ${s}
        </div>`,n?e.replaceChildren(r):a?.replaceWith(r)})(),e.classList="feds-promo",a&&e.classList.add("feds-promo--dark"),d`<div class="feds-promo-wrapper" daa-lh="promo-card">
      ${e}
    </div>`},k=async({content:e,separatorTagName:t="H5"}={})=>{const a=e.children.length>1;let n=0;for await(const r of[...e.children]){await p();const e=a?"feds-menu-column":"feds-menu-content",s=a?"feds-menu-section":"feds-menu-column",i=d`<div class="${e}"></div>`;let l,c=d`<div class="${s}"></div>`;const m={position:0},u=()=>{c.childElementCount&&i.append(c),c=d`<div class="${s}"></div>`};for(;r.children.length;){await p();const s=r.firstElementChild;if(s.matches(o.columnBreak))u(),s.remove();else if(s.tagName===t){n+=1,u(),a||(m.position=0);const t=$(s,n);if(l=d`<div class="feds-menu-items" daa-lh="${y(t.textContent.trim())}"></div>`,c.append(t,l),r.querySelector(o.columnBreak)){i.classList.add(`${e}--group`),r.querySelectorAll(o.columnBreak).length>1&&i.classList.add(`${e}--wide`);const t=document.createElement("div");t.append(...r.childNodes),l.append(t),await k({content:l})}}else if(s.matches(o.gnavPromo)){u(),m.position=0;const e=x(s,m);c.append(e)}else if(s.matches(".gnav-image")){u(),m.position=0;const e=S(s);c.append(e)}else{let e=E({elem:s,itemIndex:m});s.remove();const t=l||c;let a=null;if("P"===e.tagName&&(e=d`<li>${e.innerHTML}</li>`),"LI"===e.tagName){let e=t.querySelector("ul");e||(e=d`<ul></ul>`,t.append(e)),a=e}else a=t;a.append(e)}}i.append(c),r.replaceWith(i)}};let q=0;export default{decorateMenu:e=>l((async()=>{let t;if("syncDropdownTrigger"===e.type){const a=e.item.closest("div"),n=a.querySelector("h2");a.removeChild(n),t=d`<div class="feds-popup">
        ${a}
      </div>`,await k({content:t})}if("asyncDropdownTrigger"===e.type){performance.mark(`DecorateMenu-${q}-Start`);const a=e.item.querySelector("a");if(!(a instanceof HTMLElement))return;const l=await n({url:a.href});if(!l)return;const c=d`<div class="feds-menu-content">${l.innerHTML}</div>`;if(t=d`<div class="feds-popup">
        <div class="feds-menu-container">
          ${c}
        </div>
      </div>`,u(t,l),(e=>{const t=e.querySelector(".cross-cloud-menu");t&&(E({elem:t}),t.className="feds-crossCloudMenu-wrapper",t.querySelector("div").className="feds-crossCloudMenu",t.querySelectorAll("ul li").forEach(((e,t)=>{0===t&&e.querySelector("a")?.prepend(d`${s.home}`),e.className="feds-crossCloudMenu-item"})),e.append(t))})(t),await k({content:c}),r(t)instanceof HTMLElement){const t=()=>{e.template.style.width="",e.template.classList.remove(o.deferredActiveNavItem.slice(1))};e.template.classList.add(o.activeNavItem.slice(1)),i.matches&&(e.template.style.width=`${e.template.offsetWidth}px`,e.template.classList.add(o.deferredActiveNavItem.slice(1)),i.addEventListener("change",t,{once:!0}),window.addEventListener("feds:navOverflow",t,{once:!0}))}if(q+=1,e.template.classList.add("feds-navItem--megaMenu"),f()===q&&!g()){const e=document.querySelectorAll(".feds-nav .feds-navItem--megaMenu");h()||1!==e.length||(e[0].classList.add(o.activeNavItem.slice(1)),v(!0))}}"footerMenu"===e.type&&await k({content:e.item,separatorTagName:"H2"}),e.template?.querySelector(".feds-popup.loading")?.remove(),e.template?.append(t),"asyncDropdownTrigger"===e.type&&performance.mark(`DecorateMenu-${q}-End`)}),"Decorate menu failed","gnav-menu","i"),decorateLinkGroup:L,decorateHeadline:$};